name: Java CI with Allure

on:
  push:
    branches: [ "*" ]
    paths: [ "**", "!*.md" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Allure CLI
        run: sudo npm install -g allure-commandline --unsafe-perm=true

      - name: Run tests
        run: mvn clean test -fail-at-end

      - name: Checkout gh-pages branch (history)
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
          persist-credentials: false

      - name: Collect Allure results
        if: always()
        run: |
          mkdir -p combined-allure-results
          find . -type d -path "*/target/allure-results" -print0 | xargs -0 -I{} cp -r {}/* combined-allure-results/ 2>/dev/null || true

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: combined-allure-results
          gh_pages: gh-pages            # тут лежит старая история
          allure_report: allure-report
          allure_history: allure-history

      - name: Ensure no nested .git in publish dir
        if: always()
        run: |
          if [ -d allure-history/.git ]; then
            chmod -R u+w allure-history/.git || true
            rm -rf allure-history/.git
          fi
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          enable_jekyll: false
